db:
  production:
    adapter:  mysql2
    host:     localhost
    username: root
    password: 
    database: 
    encoding: utf8

  development:
    adapter:  mysql2
    host:     localhost
    username: root
    password: 
    database: 
    encoding: utf8